version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: onibus-express-backend
    ports:
      - "5000:5000"
    networks:
      - onibus-rede
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: onibus-express-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - VITE_USE_MSW=false
    networks:
      - onibus-rede

networks:
  onibus-rede:
    driver: bridge
